apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: spiffe-helper
networking:
    apiServerAddress: 127.0.0.1
    apiServerPort: 36443
nodes:
    - role: control-plane
    - role: worker
    - role: worker
