kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: spire-csi-driver
subjects:
    - kind: ServiceAccount
      name: spire-csi-driver
      namespace: spire-agent
roleRef:
    kind: ClusterRole
    name: spire-csi-driver
    apiGroup: rbac.authorization.k8s.io
